// ─── Enums ────────────────────────────────────────────────────────────────────

export enum MessStatus {
  PENDING_SETUP = 'PENDING_SETUP',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}

export enum MessMembershipRole {
  PRIMARY_OWNER = 'PRIMARY_OWNER',
  CO_ADMIN = 'CO_ADMIN',
}

export enum MessMembershipStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
}

export enum DirectorRelationshipStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  DECLINED = 'DECLINED',
  REVOKED = 'REVOKED',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
}

export enum BoarderMembershipStatus {
  INVITED = 'INVITED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  LEAVE_REQUESTED = 'LEAVE_REQUESTED',
  ENDED = 'ENDED',
  REMOVED = 'REMOVED',
}

export enum BoarderJoinVia {
  ADMIN_INVITE = 'ADMIN_INVITE',
  JOIN_REQUEST = 'JOIN_REQUEST',
}

export enum BoarderResidencyType {
  RESIDENT = 'RESIDENT',
  MEAL_ONLY = 'MEAL_ONLY',
}

export enum ManagerAssignmentStatus {
  PENDING_ACCEPTANCE = 'PENDING_ACCEPTANCE',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  TERMINATED_EARLY = 'TERMINATED_EARLY',
}

export enum MealType {
  BREAKFAST = 'BREAKFAST',
  LUNCH = 'LUNCH',
  DINNER = 'DINNER',
  CUSTOM = 'CUSTOM',
}

export enum MealCorrectionRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum MealRecordStatus {
  DEFAULT_ON = 'DEFAULT_ON',
  OPTED_OUT = 'OPTED_OUT',
  LOCKED = 'LOCKED',
  FINALIZED = 'FINALIZED',
  CORRECTED = 'CORRECTED',
}

export enum ExpenseDistributionMethod {
  EQUAL_SPLIT = 'EQUAL_SPLIT',
  MEAL_PROPORTIONAL = 'MEAL_PROPORTIONAL',
  DIRECT_CHARGE = 'DIRECT_CHARGE',
}

export enum ExpenseEligibleScope {
  ALL = 'ALL',
  RESIDENT_ONLY = 'RESIDENT_ONLY',
  MEAL_ONLY = 'MEAL_ONLY',
  SELECTED_MEMBERS = 'SELECTED_MEMBERS',
}

export enum ExpenseSourceType {
  MANUAL_EXTERNAL = 'MANUAL_EXTERNAL',
  LINKED_SHOP = 'LINKED_SHOP',
  OTHER = 'OTHER',
}

export enum ExpenseStatus {
  DRAFT = 'DRAFT',
  DRAFT_FROM_SHOP = 'DRAFT_FROM_SHOP',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  REVERSED = 'REVERSED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BKASH = 'BKASH',
  NAGAD = 'NAGAD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  OTHER = 'OTHER',
}

export enum PaymentChannel {
  CASH_CHANNEL = 'CASH_CHANNEL',
  DIGITAL_CHANNEL = 'DIGITAL_CHANNEL',
}

export enum PaymentStatus {
  DRAFT = 'DRAFT',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  DISPUTED = 'DISPUTED',
  REJECTED = 'REJECTED',
  REVERSED = 'REVERSED',
}

export enum AccountingPeriodStatus {
  ACTIVE = 'ACTIVE',
  PREPARING = 'PREPARING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CLOSED = 'CLOSED',
}

export enum SubscriptionStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  GRACE_PERIOD = 'GRACE_PERIOD',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum SubscriptionPlan {
  BASIC = 'BASIC',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
}

export enum FundHandoverItemType {
  CASH_IN_HAND = 'CASH_IN_HAND',
  ADVANCE_FUND = 'ADVANCE_FUND',
  PETTY_CASH = 'PETTY_CASH',
  PENDING_COLLECTION = 'PENDING_COLLECTION',
  OTHER = 'OTHER',
}

export enum FundHandoverStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  DISPUTED = 'DISPUTED',
  ACCEPTED = 'ACCEPTED',
  ADJUSTED = 'ADJUSTED',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
  ESCALATED = 'ESCALATED',
}

export enum GuestMealChargingPolicy {
  CHARGE_TO_HOST = 'CHARGE_TO_HOST',
  SHARED_POOL = 'SHARED_POOL',
  CUSTOM_CONFIGURED = 'CUSTOM_CONFIGURED',
}

export enum ShopStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
}

export enum BillingAccountStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
}

export enum GuestMealStatus {
  RECORDED = 'RECORDED',
  FINALIZED = 'FINALIZED',
  DISPUTED = 'DISPUTED',
}

export enum ShopOrderStatus {
  DRAFT = 'DRAFT',
  PLACED = 'PLACED',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum IntegrationEventType {
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED',
  REFUND_ISSUED = 'REFUND_ISSUED',
}

export enum IntegrationProcessingStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  MESS_CREATED = 'MESS_CREATED',
  MESS_UPDATED = 'MESS_UPDATED',
  MESS_STATUS_CHANGED = 'MESS_STATUS_CHANGED',
  MESS_MEMBERSHIP_INVITED = 'MESS_MEMBERSHIP_INVITED',
  MESS_MEMBERSHIP_ACCEPTED = 'MESS_MEMBERSHIP_ACCEPTED',
  MESS_MEMBERSHIP_REVOKED = 'MESS_MEMBERSHIP_REVOKED',
  DIRECTOR_INVITED = 'DIRECTOR_INVITED',
  DIRECTOR_ACCEPTED = 'DIRECTOR_ACCEPTED',
  DIRECTOR_REVOKED = 'DIRECTOR_REVOKED',
  DIRECTOR_SUSPENDED = 'DIRECTOR_SUSPENDED',
  BOARDER_INVITED = 'BOARDER_INVITED',
  BOARDER_INVITE_DECLINED = 'BOARDER_INVITE_DECLINED',
  BOARDER_JOIN_REQUESTED = 'BOARDER_JOIN_REQUESTED',
  BOARDER_JOIN_REJECTED = 'BOARDER_JOIN_REJECTED',
  BOARDER_APPROVED = 'BOARDER_APPROVED',
  BOARDER_REMOVED = 'BOARDER_REMOVED',
  BOARDER_LEAVE_REQUESTED = 'BOARDER_LEAVE_REQUESTED',
  BOARDER_LEFT = 'BOARDER_LEFT',
  BOARDER_RESIDENCY_CHANGED = 'BOARDER_RESIDENCY_CHANGED',
  MANAGER_ASSIGNED = 'MANAGER_ASSIGNED',
  MANAGER_ACCEPTED = 'MANAGER_ACCEPTED',
  MANAGER_COMPLETED = 'MANAGER_COMPLETED',
  MANAGER_TERMINATED = 'MANAGER_TERMINATED',
  MEAL_CONFIG_UPDATED = 'MEAL_CONFIG_UPDATED',
  MEAL_OPTED_OUT = 'MEAL_OPTED_OUT',
  MEAL_OPT_IN_REVERTED = 'MEAL_OPT_IN_REVERTED',
  MEAL_LOCKED = 'MEAL_LOCKED',
  MEAL_CORRECTION_REQUESTED = 'MEAL_CORRECTION_REQUESTED',
  MEAL_CORRECTED = 'MEAL_CORRECTED',
  MEAL_CORRECTION_REJECTED = 'MEAL_CORRECTION_REJECTED',
  MEAL_FINALIZED = 'MEAL_FINALIZED',
  GUEST_MEAL_RECORDED = 'GUEST_MEAL_RECORDED',
  GUEST_MEAL_DISPUTED = 'GUEST_MEAL_DISPUTED',
  EXPENSE_CATEGORY_CREATED = 'EXPENSE_CATEGORY_CREATED',
  EXPENSE_CATEGORY_UPDATED = 'EXPENSE_CATEGORY_UPDATED',
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_CONFIRMED = 'EXPENSE_CONFIRMED',
  EXPENSE_REJECTED = 'EXPENSE_REJECTED',
  EXPENSE_REVERSED = 'EXPENSE_REVERSED',
  EXPENSE_ALLOCATED = 'EXPENSE_ALLOCATED',
  PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_DISPUTED = 'PAYMENT_DISPUTED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  PAYMENT_REVERSED = 'PAYMENT_REVERSED',
  PERIOD_CREATED = 'PERIOD_CREATED',
  PERIOD_PREPARING = 'PERIOD_PREPARING',
  PERIOD_UNDER_REVIEW = 'PERIOD_UNDER_REVIEW',
  PERIOD_CLOSED = 'PERIOD_CLOSED',
  PERIOD_ADJUSTMENT = 'PERIOD_ADJUSTMENT',
  DISPUTE_RAISED = 'DISPUTE_RAISED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  DISPUTE_DISMISSED = 'DISPUTE_DISMISSED',
  HANDOVER_SUBMITTED = 'HANDOVER_SUBMITTED',
  HANDOVER_ACCEPTED = 'HANDOVER_ACCEPTED',
  HANDOVER_DISPUTED = 'HANDOVER_DISPUTED',
  HANDOVER_ADJUSTED = 'HANDOVER_ADJUSTED',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPGRADED = 'SUBSCRIPTION_UPGRADED',
  SUBSCRIPTION_DOWNGRADED = 'SUBSCRIPTION_DOWNGRADED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_SUSPENDED = 'SUBSCRIPTION_SUSPENDED',
  PLATFORM_ADMIN_ACTION = 'PLATFORM_ADMIN_ACTION',
}

// ─── Common Types ─────────────────────────────────────────────────────────────

export interface PaginationMeta {
  total: number;
  page: number;
  limit: number;
  hasNextPage: boolean;
  hasPrevPage: boolean;
}

export interface PaginatedResponse<T> {
  data: T[];
  meta: PaginationMeta;
}

export interface ApiResponse<T = void> {
  success: boolean;
  data?: T;
  message?: string;
}

export interface ApiError {
  success: false;
  error: {
    code: string;
    message: string;
    details?: Record<string, string[]>;
  };
}

// ─── Auth Types ───────────────────────────────────────────────────────────────

export interface JwtPayload {
  sub: string; // userId
  email: string;
  iat: number;
  exp: number;
}

export interface AuthTokens {
  accessToken: string;
  expiresIn: number;
}
